<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Stationeers.User.props" />

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>NetworkPainter</AssemblyName>
    <RootNamespace>NetworkPainter</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(StationeersDirectory)/BepInEx/core/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(StationeersDirectory)/rocketstation_Data/Managed/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(StationeersDirectory)/rocketstation_Data/Managed/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(StationeersDirectory)/rocketstation_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="LaunchPadBooster">
      <HintPath>$(StationeersDirectory)/BepInEx/plugins/StationeersLaunchPad/LaunchPadBooster.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
